title: test
exclude:
  - _RIOT
  - _tools
  - Makefile
  - README.md
include:
  - .well-known
keep_files:
  - .well-known

sass:
    sass_dir: _sass
collections:
    use_cases:
        output: true
    faqs:
        output: true

defaults:
  - scope:
      path: ""
      type: "use_cases"
    values:
      layout: "use-case"

highlighter: rouge

# enable/disable the blog section in the index
blog: false
